[[main]]
name = "Blog"
pageRef = "posts"
weight = 1

# Hide Projects section temporarily until it gets more full
# [[main]]
# name = "Projects"
# pageRef = "projects"
# weight = 2


[[main]]
name = "About Me"
pageRef = "about"
weight = 3

[[main]]
name = "Resume"
pageRef = "resume"
weight = 4


[[main]]
name = "Contact"
pageRef = "contact"
weight = 5

[[footer]]
none = "none"
